parameters:
  environment: <%= ENV['RACK_ENV'] %>
services:
  elasticsearch_configuration:
    class: 'Configurations::Elasticsearch'
    file_path: './lib/configurations/elasticsearch'
    arguments:
      - '%environment%'
  elasticsearch_client:
    class: 'ElasticsearchClient'
    file_path: './lib/elasticsearch_client'
    arguments:
      - '@elasticsearch_configuration'
  global_finder:
    class: 'Finders::GlobalFinder'
    file_path: './lib/finders/global_finder'
    arguments:
      - '@elasticsearch_client'
  trending_finder:
    class: 'Finders::TrendingFinder'
    file_path: './lib/finders/trending_finder'
    arguments:
      - '@elasticsearch_client'
  technology_finder:
    class: 'Finders::TechnologyFinder'
    file_path: './lib/finders/technology_finder'
    arguments:
      - '@elasticsearch_client'
